llms/bedrock: Fixed error when using Claude3 model and giving MessageContent with images (#713)
* llms/bedrock/internal/bedrockclient: Currently, antropicBinGenerationInputSource.Type is fixed to base64.

According to the Claude3 API documentation, the current image input format only accepts base64.
https://docs.anthropic.com/claude/reference/messages_post
Therefore, the existing implementation will generate the following error when making a request with an image

````
operation error Bedrock Runtime: InvokeModel, https response error StatusCode: 400, RequestID: 00000000-0000-0000-0000-0000000000000000,. ValidationException: messages.0.content.0.image.source: Input tag 'image' found using 'type' does not match any of the expected tags: 'base64'
exit status 1
```

This commit corrects the above error and allows Claude3 to be called via Bedrock with image input.

* llms/bedrock/internal/bedrockclient: Consider MultiPart MessageContent.

The current implementation of llms/bedrock/internal/bedrockclient/provider_anthropic.processInputMessagesAnthropic does not seem to account for MessageContent containing multiple Part MessageContent with multiple parts.

Passing a MessageContent like the following will result in an error.
```
		[]llms.MessageContent{
			{
				Role: schema.ChatMessageTypeHuman,.
				Parts: []llms.ContentPart{
					llms.BinaryPart("image/png", image), llms.
					TextPart("Please text what is written on this image."), llms.
				}, }
			}, }
		}, }
```

```
operation error Bedrock Runtime: InvokeModel, https response error StatusCode: 400, RequestID: 00000000-0000-0000-0000-0000000000000000, ValidationException: messages: roles must alternate between "user" and "assistant", but found multiple "user" roles in a row
````

This is due to the fact that []llms.MessageContent is converted to []bedrockclient.Message.
So, this commit fixes the above by modifying the procssInputMessagesAnthropic code.
Chunking the argument []bedrockclient.Message with a group of the same Role.
Then, each Chunk is converted to anthropicTextGenerationInputMessage.

* llms/bedrock/internal/bedrockclient: fix lint for Consider pre-allocating `currentChunk` (prealloc)

golang-ci lint error message
```
Error: Consider pre-allocating `currentChunk` (prealloc)
```
fix this

* llms/bedrock/internal/bedrockclient: fix lint goconst

fix golang lint
```
string `text` has 3 occurrences, but such constant `AnthropicMessageTypeText` already exists (goconst)
```